export const ADD_TODO = 'TODO_APP/ADD_TODO';
export const REMOVE_TODO = 'TODO_APP/REMOVE_TODO';
export const EDIT_TODO = 'TODO_APP/EDIT_TODO';
export const SHOW_EDIT_MODAL = 'TODO_APP/SHOW_EDIT_MODAL';
export const HIDE_EDIT_MODAL = 'TODO_APP/HIDE_EDIT_MODAL';
export const TOGGLE_COMPLETE_CHECKBOX = 'TODO_APP/TOGGLE_COMPLETE_CHECKBOX';